version: "2"

services:
  web:
    image: nginx:latest
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
    container_name: nginx-srv
  php:
    image: php:fpm
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - ./code:/code
    networks:
      - code-network
    container_name: php-srv
  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
      MYSQL_USER: developer
      MYSQL_PASSWORD: dev
    ports:
      - "9906:3306"
    container_name: mysql-srv

networks:
  code-network:
    driver: bridge
